### ISSUE TITLE
Unauthorized Query

### ISSUE THREAD

**Issue by 913728188** [trulia/trulia-java-rets-client#12]
when i run this example,i got "Unauthorized Query
	at org.realtors.rets.client.InvalidReplyCodeHandler$1.invalidRetsReplyCode(InvalidReplyCodeHandler.java:6)
	at org.realtors.rets.client.SearchResultHandler.startElement(SearchResultHandler.java:78)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:766)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1339)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$ContentDriver.scanRootElementHook(XMLDocumentScannerImpl.java:1289)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3132)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:852)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at org.realtors.rets.client.SearchResultHandler.parse(SearchResultHandler.java:268)
	at org.realtors.rets.client.SearchResultHandler.parse(SearchResultHandler.java:243)
	at org.realtors.rets.client.RetsTransport.search(RetsTransport.java:237)
	at org.realtors.rets.client.RetsSession.search(RetsSession.java:335)
	at org.realtors.rets.client.RetsSession.search(RetsSession.java:320)
	at org.realtors.rets.examples.RetsSearchExample.main(RetsSearchExample.java:59)"

**Comment by 913728188** [comment]
i had server host and account,what's the probram?
